// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for kickboxing-management project
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_k4-SXjh_aWQsWOOVzFWPeBxxx_mHL-Q',
    appId: '1:32797639221:web:your-web-app-id', // Add web app to Firebase to get this
    messagingSenderId: '32797639221',
    projectId: 'kickboxing-management',
    authDomain: 'kickboxing-management.firebaseapp.com',
    storageBucket: 'kickboxing-management.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_k4-SXjh_aWQsWOOVzxxxeBVHC_mHL-Q',
    appId: '1:32797639221:android:f17e2c9b132d8a7f72e77c',
    messagingSenderId: '32797639221',
    projectId: 'kickboxing-management',
    storageBucket: 'kickboxing-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_k4-SXjh_aWQsxxxVzFWPeBVHC_mHL-Q',
    appId: '1:32797639221:ios:your-ios-app-id', // Add iOS app to Firebase to get this
    messagingSenderId: '32797639221',
    projectId: 'kickboxing-management',
    storageBucket: 'kickboxing-management.firebasestorage.app',
    iosClientId: 'your-ios-client-id', // Add iOS app to Firebase to get this
    iosBundleId: 'com.example.newManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_k4-SXjh_axxxWOOVzFWPeBVHC_mHL-Q',
    appId: '1:32797639221:ios:your-macos-app-id', // Add macOS app to Firebase to get this
    messagingSenderId: '32797639221',
    projectId: 'kickboxing-management',
    storageBucket: 'kickboxing-management.firebasestorage.app',
    iosClientId: 'your-macos-client-id', // Add macOS app to Firebase to get this
    iosBundleId: 'com.example.newManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_k4-SXjh_aWQsWxxxzFWPeBVHC_mHL-Q',
    appId: '1:32797639221:windows:your-windows-app-id', // Add Windows app to Firebase to get this
    messagingSenderId: '32797639221',
    projectId: 'kickboxing-management',
    storageBucket: 'kickboxing-management.firebasestorage.app',
  );
} 
